### ISSUE TITLE
Console.log 

### ISSUE THREAD

**Issue by grantyi** [NoPPT/react-native-zhb-actionsheet#2]
https://github.com/NoPPT/react-native-zhb-actionsheet/blob/23e4158ae05d908523246cd3c320ad2edf8f7d98/src/index.js#L199

Not a huge issue, but this console.log is logging every second. Should be removed

**Comment by NoPPT** [comment]
[#505fa4e](https://github.com/NoPPT/react-native-zhb-actionsheet/pull/3/commits/505fa4eb122ab6a2106d15b05696efa23eb9eaa6)
